WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.14', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f483bd76be0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.14', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f483bd1a580>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
INFO:root:RPC client connection error - port=1234, server='192.168.40.14', ssl=True
