WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.23', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb845d5e50>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.23', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb845627f0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
